Repository abelRoland/flex-panel, pull requests merged in 2020-08, with the labels that each got.

#8 CSS
  .vscode/settings.json
  images/five.jpeg
  images/four.jpeg
  images/one.jpeg
  images/three.jpeg
  images/two.jpeg
  index.html
  style.css
Labels: CSS

#4 Adding listeners
  index.html
  scripts/listeners/listeners.js
  scripts/listeners/starter.js
Labels: JavaScript

#7 Html
  index.html
Labels: Html

#2 Added toggle open function
  index.html
  scripts/handlers/handlers.js
Labels: JavaScript

#12 Readme
  README.md
  index.html
  scripts/handlers/handlers.js
Labels: documentation

#14 Writing dev-strategy
  development-strategy.md
Labels: documentation
